language: csharp

sudo: false  # use the new container-based Travis infrastructure
mono:
  - 4.2.3

env:
  - PAKET_VERSION=
    PAKET_UPDATE=
  - PAKET_VERSION=prerelease
    PAKET_UPDATE=y

script: 
  - ./build.sh Travis

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a43d3bdbdee36cd658ea
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # default: false
